# Generated by Django 5.1.7 on 2025-05-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Например: ул. Примерная, 10', max_length=255)),
                ('working_hours', models.CharField(help_text='Например: 10:00-20:00', max_length=50)),
                ('phone', models.CharField(help_text='Например: +7 951 123-45-67', max_length=20)),
                ('contact_phone', models.CharField(blank=True, help_text='Дополнительный контактный номер (необязательно)', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='show_status_notification',
            field=models.BooleanField(default=False),
        ),
    ]
