# Generated by Django 5.1.1 on 2025-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paymentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('ДСП', 'ДСП'), ('МДФ', 'МДФ'), ('Натуральное дерево', 'Натуральное дерево')], max_length=50),
        ),
    ]
