# Generated by Django 5.1.7 on 2025-05-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts_order_show_status_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='show_status_notification',
        ),
    ]
